FIRST_LAYER_TO_GENERATE = 2
LAST_LAYER_TO_GENERATE = -1
DEBUGGING = True
LAYERS_TO_DEBUG = [2]
START_CODE_GENERATION_SIGNAL = 'begin_code_generation'
END_CODE_GENERATION_SIGNAL = 'end_code_generation'
