{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: clang++-10 build active file",
            "command": "/usr/bin/g++",
            "args": [
                "-g",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/model_components/utils/utils.cpp ",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/model_components/model/SEML/imp/seml.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/model_components/layers/impl/pw_conv.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/client/prepare_weights_and_input.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/model_components/layers/impl/pooling.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/model_components/layers/impl/norm_act.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/client/cpp_main_file.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/model_components/layers/impl/dw_conv_v5.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/model_components/layers/headers/dw_conv.h",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/model_components/layers/impl/conv.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/model_components/model/SESL/impl/cnn_pipeline_6_mob_v2.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/model_components/model/fused_bottlenecks/bottleneck_kernels.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/model_components/model/fused_bottlenecks/bottleneck_0.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/model_components/model/fused_bottlenecks/bottleneck_1.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/model_components/model/fused_bottlenecks/bottleneck_2.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/model_components/model/fused_bottlenecks/bottlenecks_chain.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/model_components/model/fused_bottlenecks/bottlenecks_chain_0_1_2.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/tests/test_utils.cpp",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/tests/main_tester.cpp",
                "-o",
                "/media/SSD2TB/fareed/wd/cpu_cnn_layers/tests/main_tester"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}